/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online_shopping_system;

import java.sql.*; // Uses Connection, PreparedStatement, and ResultSet
import javax.swing.*; // Uses JOptionPane and JFrame

/**
 *
 * @author MIRAFLORES, JOHN PAUL S. - BSIT 2F
 */
public class AddtoCart extends javax.swing.JFrame {

    private static final String URL = "jdbc:mysql://localhost:3306/online_shopping_system?allowPublicKeyRetrieval=true&useSSL=false";
    private static final String USERNAME = "root";
    private static final String PASSWORD = "@theHouseof25";

    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rset = null;

    /**
     * Creates new form AddtoCart
     */
    public AddtoCart() {
        initComponents();
    }

    int xMouse;
    int yMouse;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productDetails = new javax.swing.JPanel();
        Sparkle = new javax.swing.JLabel();
        productTitle = new javax.swing.JLabel();
        jBrand = new javax.swing.JLabel();
        jlblName = new javax.swing.JLabel();
        jlblPrice = new javax.swing.JLabel();
        jlblStock = new javax.swing.JLabel();
        jlblBrand = new javax.swing.JLabel();
        decrementBtn = new javax.swing.JButton();
        textCQuant = new javax.swing.JTextField();
        incrementBtn = new javax.swing.JButton();
        cartQuantlbl = new javax.swing.JLabel();
        cnclBTN = new javax.swing.JButton();
        atcBTN = new javax.swing.JButton();
        jlblID = new javax.swing.JLabel();
        jID = new javax.swing.JLabel();
        jIMG = new javax.swing.JLabel();
        jPrice = new javax.swing.JLabel();
        jStock = new javax.swing.JLabel();
        jCurrency = new javax.swing.JLabel();
        jName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productDetails.setBackground(new java.awt.Color(108, 122, 137));
        productDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        productDetails.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                productDetailsMouseDragged(evt);
            }
        });
        productDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                productDetailsMousePressed(evt);
            }
        });
        productDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sparkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online_shopping_system/Assets/Sparkle.gif"))); // NOI18N
        productDetails.add(Sparkle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        productTitle.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        productTitle.setForeground(new java.awt.Color(255, 255, 255));
        productTitle.setText("JEWELRY DETAILS");
        productDetails.add(productTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jBrand.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 12)); // NOI18N
        jBrand.setForeground(new java.awt.Color(255, 255, 255));
        jBrand.setText("DETAILS");
        productDetails.add(jBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 160, -1));

        jlblName.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        jlblName.setForeground(new java.awt.Color(255, 255, 255));
        jlblName.setText("Name: ");
        productDetails.add(jlblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 50, -1));

        jlblPrice.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        jlblPrice.setForeground(new java.awt.Color(255, 255, 255));
        jlblPrice.setText("Price: ");
        productDetails.add(jlblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 50, -1));

        jlblStock.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        jlblStock.setForeground(new java.awt.Color(255, 255, 255));
        jlblStock.setText("Stock: ");
        productDetails.add(jlblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 50, -1));

        jlblBrand.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        jlblBrand.setForeground(new java.awt.Color(255, 255, 255));
        jlblBrand.setText("Brand: ");
        productDetails.add(jlblBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 50, -1));

        decrementBtn.setBackground(new java.awt.Color(0, 102, 204));
        decrementBtn.setForeground(new java.awt.Color(255, 255, 255));
        decrementBtn.setText("-");
        decrementBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        decrementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decrementBtnActionPerformed(evt);
            }
        });
        productDetails.add(decrementBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 20, 30));

        textCQuant.setEditable(false);
        textCQuant.setBackground(new java.awt.Color(0, 0, 0));
        textCQuant.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        textCQuant.setForeground(new java.awt.Color(255, 255, 255));
        textCQuant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        productDetails.add(textCQuant, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 94, 30));

        incrementBtn.setBackground(new java.awt.Color(0, 102, 204));
        incrementBtn.setForeground(new java.awt.Color(255, 255, 255));
        incrementBtn.setText("+");
        incrementBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        incrementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incrementBtnActionPerformed(evt);
            }
        });
        productDetails.add(incrementBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 20, 30));

        cartQuantlbl.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        cartQuantlbl.setForeground(new java.awt.Color(255, 255, 255));
        cartQuantlbl.setText("Quantity: ");
        productDetails.add(cartQuantlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 30));

        cnclBTN.setBackground(new java.awt.Color(0, 102, 204));
        cnclBTN.setForeground(new java.awt.Color(255, 255, 255));
        cnclBTN.setText("Cancel");
        cnclBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cnclBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnclBTNActionPerformed(evt);
            }
        });
        productDetails.add(cnclBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 90, -1));

        atcBTN.setBackground(new java.awt.Color(0, 102, 204));
        atcBTN.setForeground(new java.awt.Color(255, 255, 255));
        atcBTN.setText("Add to Cart");
        atcBTN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        atcBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atcBTNActionPerformed(evt);
            }
        });
        productDetails.add(atcBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 90, -1));

        jlblID.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        jlblID.setForeground(new java.awt.Color(255, 255, 255));
        jlblID.setText("ID: ");
        productDetails.add(jlblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 50, -1));

        jID.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 12)); // NOI18N
        jID.setForeground(new java.awt.Color(255, 255, 255));
        jID.setText("DETAILS");
        productDetails.add(jID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 160, -1));

        jIMG.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        productDetails.add(jIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 210, 200));

        jPrice.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 12)); // NOI18N
        jPrice.setForeground(new java.awt.Color(255, 255, 255));
        jPrice.setText("DETAILS");
        productDetails.add(jPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 160, -1));

        jStock.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 12)); // NOI18N
        jStock.setForeground(new java.awt.Color(255, 255, 255));
        jStock.setText("DETAILS");
        productDetails.add(jStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 160, -1));

        jCurrency.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 12)); // NOI18N
        jCurrency.setForeground(new java.awt.Color(255, 255, 255));
        jCurrency.setText("PHP");
        productDetails.add(jCurrency, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 20, -1));

        jName.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 12)); // NOI18N
        jName.setForeground(new java.awt.Color(255, 255, 255));
        jName.setText("DETAILS");
        productDetails.add(jName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 340, -1));

        getContentPane().add(productDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private static int num;
    private void decrementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decrementBtnActionPerformed
        num--;
        textCQuant.setText("" + num);
        if (num <= 0) {
            textCQuant.setText("ERROR!");
            JOptionPane.showMessageDialog(null, "DOESN'T DEFINE VALUE!", "ERROR!", 0);
            num = 1;
            textCQuant.setText("" + num);
        }
    }//GEN-LAST:event_decrementBtnActionPerformed

    private void incrementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incrementBtnActionPerformed
        num++;
        textCQuant.setText("" + num);

        int stock = Integer.parseInt(jStock.getText());
        int quantity = Integer.parseInt(textCQuant.getText());

        if (quantity > stock) {
            textCQuant.setText("ERROR!");
            JOptionPane.showMessageDialog(null, "Please select at least equal to the\nnumber of stock!");
            num--;
            textCQuant.setText("" + num);
        }
    }//GEN-LAST:event_incrementBtnActionPerformed

    private void atcBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atcBTNActionPerformed
        try {

            String quantity = textCQuant.getText();
            String cid = JPsOnlineShopping.lblID.getText();
            String productname = jName.getText();
            String productprice = jPrice.getText();
            String productid = jID.getText();

            conn = DriverManager.getConnection(URL, USERNAME, PASSWORD);
            ps = conn.prepareStatement("INSERT INTO cart "
                    + "(CART_QUANT, CUSTOMER_ID,CART_PRODUCTNAME,CART_PRODUCTPRICE,PRODUCT_ID) "
                    + "VALUES(?,?,?,?,?)");

            ps.setString(1, quantity);
            ps.setString(2, cid);
            ps.setString(3, productname);
            ps.setString(4, productprice);
            ps.setString(5, productid);

            int c = ps.executeUpdate();

            if (c != 0) {
                JOptionPane.showMessageDialog(null, "Added to Cart!");

                ps = conn.prepareStatement("UPDATE PRODUCT SET PRODUCT_STOCK = PRODUCT_STOCK - ? WHERE PRODUCT_ID = ?");

                ps.setString(1, quantity);
                ps.setString(2, productid);

                ps.executeUpdate();

                num = 0;
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Failed to add!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please add a quantity value to buy!");
        }
    }//GEN-LAST:event_atcBTNActionPerformed
    private JFrame frame;
    private void cnclBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnclBTNActionPerformed
        frame = new JFrame("Close");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to cancel?", "Adding to cart",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_cnclBTNActionPerformed

    private void productDetailsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productDetailsMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_productDetailsMousePressed

    private void productDetailsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productDetailsMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_productDetailsMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddtoCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddtoCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddtoCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddtoCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddtoCart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Sparkle;
    private javax.swing.JButton atcBTN;
    private javax.swing.JLabel cartQuantlbl;
    private javax.swing.JButton cnclBTN;
    private javax.swing.JButton decrementBtn;
    private javax.swing.JButton incrementBtn;
    public static javax.swing.JLabel jBrand;
    public static javax.swing.JLabel jCurrency;
    public static javax.swing.JLabel jID;
    public static javax.swing.JLabel jIMG;
    public static javax.swing.JLabel jName;
    public static javax.swing.JLabel jPrice;
    public static javax.swing.JLabel jStock;
    private javax.swing.JLabel jlblBrand;
    private javax.swing.JLabel jlblID;
    private javax.swing.JLabel jlblName;
    private javax.swing.JLabel jlblPrice;
    private javax.swing.JLabel jlblStock;
    private javax.swing.JPanel productDetails;
    private javax.swing.JLabel productTitle;
    public static javax.swing.JTextField textCQuant;
    // End of variables declaration//GEN-END:variables
}
