/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online_shopping_system;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.*; // gets JFrame and JOptionPane
import java.sql.*;
import java.util.logging.*; //gets Level and Logger

/**
 *
 * @author MIRAFLORES, JOHN PAUL S. - BSIT 2F
 */
public class LoginSystem extends javax.swing.JFrame {

    /**
     * Creates new form LoginSystem
     */
    private static final String URL = "jdbc:mysql://localhost:3306/online_shopping_system?allowPublicKeyRetrieval=true&useSSL=false";
    private static final String USERNAME = "root";
    private static final String PASSWORD = "@theHouseof25";
    private static int tries = 3;

    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rset = null;

    public LoginSystem() {
        initComponents();
        jtxtPassword.setEchoChar('●');
        this.setSize(926, 546);
        String underline = "<html><u>click here to create!</u></html>";
        registerLink.setText(underline);
    }

    int xMouse;
    int yMouse;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HealPanel = new javax.swing.JPanel();
        jBtnClose = new javax.swing.JButton();
        jBtnMinimize = new javax.swing.JButton();
        HeadLabel = new javax.swing.JLabel();
        LoginPanel = new javax.swing.JPanel();
        jlblPass = new javax.swing.JLabel();
        jtxtUsername = new javax.swing.JTextField();
        jtxtPassword = new javax.swing.JPasswordField();
        jLoginButton = new javax.swing.JButton();
        jlblQuestion = new javax.swing.JLabel();
        registerLink = new javax.swing.JLabel();
        jicoUser = new javax.swing.JLabel();
        jlblPassword = new javax.swing.JLabel();
        jlblUsername = new javax.swing.JLabel();
        jShowPass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        HealPanel.setBackground(new java.awt.Color(15, 45, 66));
        HealPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HealPanelMouseDragged(evt);
            }
        });
        HealPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HealPanelMousePressed(evt);
            }
        });
        HealPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnClose.setBackground(new java.awt.Color(0, 102, 204));
        jBtnClose.setFont(new java.awt.Font("Gulim", 0, 18)); // NOI18N
        jBtnClose.setForeground(new java.awt.Color(255, 255, 255));
        jBtnClose.setText("x");
        jBtnClose.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCloseActionPerformed(evt);
            }
        });
        HealPanel.add(jBtnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 24, 27, -1));

        jBtnMinimize.setBackground(new java.awt.Color(0, 102, 204));
        jBtnMinimize.setFont(new java.awt.Font("Gulim", 0, 18)); // NOI18N
        jBtnMinimize.setForeground(new java.awt.Color(255, 255, 255));
        jBtnMinimize.setText("-");
        jBtnMinimize.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMinimizeActionPerformed(evt);
            }
        });
        HealPanel.add(jBtnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(823, 24, 27, -1));

        HeadLabel.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        HeadLabel.setForeground(new java.awt.Color(255, 255, 255));
        HeadLabel.setText("JP's JEWELRY SHOPPING | LOGIN");
        HealPanel.add(HeadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 22, -1, -1));

        LoginPanel.setBackground(new java.awt.Color(108, 122, 137));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblPass.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jlblPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online_shopping_system/Assets/PASSWORDIcon.gif"))); // NOI18N
        LoginPanel.add(jlblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 194, -1, -1));

        jtxtUsername.setBackground(new java.awt.Color(15, 45, 66));
        jtxtUsername.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jtxtUsername.setForeground(new java.awt.Color(153, 153, 153));
        jtxtUsername.setText("type your username here");
        jtxtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtUsernameFocusLost(evt);
            }
        });
        jtxtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtUsernameKeyPressed(evt);
            }
        });
        LoginPanel.add(jtxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 110, 342, -1));

        jtxtPassword.setBackground(new java.awt.Color(15, 45, 66));
        jtxtPassword.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jtxtPassword.setForeground(new java.awt.Color(153, 153, 153));
        jtxtPassword.setText("●●●●●●●●");
        jtxtPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtPasswordFocusLost(evt);
            }
        });
        jtxtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtPasswordKeyPressed(evt);
            }
        });
        LoginPanel.add(jtxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 232, 342, -1));

        jLoginButton.setBackground(new java.awt.Color(15, 45, 66));
        jLoginButton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        jLoginButton.setText("LOGIN");
        jLoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonActionPerformed(evt);
            }
        });
        LoginPanel.add(jLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 310, -1, -1));

        jlblQuestion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblQuestion.setForeground(new java.awt.Color(255, 255, 255));
        jlblQuestion.setText("dont have an account yet?");
        LoginPanel.add(jlblQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 414, -1, -1));

        registerLink.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        registerLink.setForeground(new java.awt.Color(255, 255, 255));
        registerLink.setText("click here to create!");
        registerLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerLinkMouseClicked(evt);
            }
        });
        LoginPanel.add(registerLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 414, -1, -1));

        jicoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online_shopping_system/Assets/USERNAMEIcon.gif"))); // NOI18N
        jicoUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, null));
        LoginPanel.add(jicoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 76, 100, 100));

        jlblPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblPassword.setForeground(new java.awt.Color(255, 255, 255));
        jlblPassword.setText("password:");
        LoginPanel.add(jlblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 209, -1, -1));

        jlblUsername.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblUsername.setForeground(new java.awt.Color(255, 255, 255));
        jlblUsername.setText("username: ");
        LoginPanel.add(jlblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 87, -1, -1));

        jShowPass.setBackground(new java.awt.Color(15, 45, 66));
        jShowPass.setForeground(new java.awt.Color(255, 255, 255));
        jShowPass.setText("show password");
        jShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowPassActionPerformed(evt);
            }
        });
        LoginPanel.add(jShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HealPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HealPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private JFrame frame;
    private void jBtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCloseActionPerformed
        frame = new JFrame("Close");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit?", "Online Shopping",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jBtnCloseActionPerformed

    private void jBtnMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMinimizeActionPerformed
        this.setState(frame.ICONIFIED);
    }//GEN-LAST:event_jBtnMinimizeActionPerformed

    private void jShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowPassActionPerformed
        if (jShowPass.isSelected()) {
            jtxtPassword.setEchoChar((char) 0);
        } else {
            jtxtPassword.setEchoChar('●');
        }
    }//GEN-LAST:event_jShowPassActionPerformed

    private void registerLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLinkMouseClicked
        RegisterForm rf = new RegisterForm();
        rf.setVisible(true);
        rf.setLocationRelativeTo(this);
        rf.setSize(926, 546);
        this.dispose();
        rf.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_registerLinkMouseClicked

    private void jtxtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtUsernameFocusGained
        if (jtxtUsername.getText().trim().toLowerCase().equals("type your username here")) {
            jtxtUsername.setText("");
            jtxtUsername.setForeground(Color.white);
        }
    }//GEN-LAST:event_jtxtUsernameFocusGained

    private void jtxtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtUsernameFocusLost
        if (jtxtUsername.getText().trim().equals("")
                || jtxtUsername.getText().trim().toLowerCase().equals("type your username here")) {
            jtxtUsername.setText("type your username here");
            jtxtUsername.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jtxtUsernameFocusLost

    private void jtxtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPasswordFocusGained

        String password = String.valueOf(jtxtPassword.getPassword());

        if (password.trim().toLowerCase().equals("●●●●●●●●")) {
            jtxtPassword.setText("");
            jtxtPassword.setForeground(Color.white);
        }
    }//GEN-LAST:event_jtxtPasswordFocusGained

    private void jtxtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPasswordFocusLost

        String password = String.valueOf(jtxtPassword.getPassword());

        if (password.trim().equals("") || password.trim().toLowerCase().equals("●●●●●●●●")) {
            jtxtPassword.setText("●●●●●●●●");
            jtxtPassword.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jtxtPasswordFocusLost

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        try {
            String username = jtxtUsername.getText();
            String password = String.valueOf(jtxtPassword.getPassword());

            conn = DriverManager.getConnection(URL, USERNAME, PASSWORD);
            ps = conn.prepareStatement("SELECT * FROM customer "
                    + "WHERE username = ? AND BINARY password = ?");

            ps.setString(1, username);
            ps.setString(2, password);

            rset = ps.executeQuery();

            if (rset.next()) {
                if (jtxtUsername.getText().equals("admin") && jtxtUsername.getText().equals("admin")) {
                    JOptionPane.showMessageDialog(null, "Logged in successfully!", "WELCOME ADMIN!", 1);
                    adminPanel aP = new adminPanel();
                    aP.setVisible(true);
                    aP.setLocationRelativeTo(this);
                    aP.setSize(926, 546);
                    this.dispose();

                    adminPanel.WelcomeUser.setText("WELCOME, " + LoginSystem.jtxtUsername.getText().toUpperCase() + "!");
                } else {
                    JOptionPane.showMessageDialog(null, "Logged in successfully!", "SUCCESS!", 1);
                    JPsOnlineShopping jpos = new JPsOnlineShopping();
                    jpos.setVisible(true);
                    jpos.setLocationRelativeTo(this);
                    jpos.setSize(926, 546);
                    this.dispose();

                    String cid = rset.getString("customer_id");
                    String address = rset.getString("address");
                    JPsOnlineShopping.lblID.setText(cid);
                    JPsOnlineShopping.CAddress.setText(address);

                    JPsOnlineShopping.WelcomeUser.setText("welcome, " + LoginSystem.jtxtUsername.getText().toLowerCase() + "!");
                    jpos.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Invalid username/password!", "LOGIN FAILED!", 2);
                tries--;
                if (tries == 0) {
                    tries = 3;
                    JOptionPane.showMessageDialog(null, "Redirecting you to create a new account!", "LOGIN FAILED!", 2);
                    RegisterForm rf = new RegisterForm();
                    rf.setVisible(true);
                    rf.setLocationRelativeTo(this);
                    rf.setSize(926, 546);
                    this.dispose();
                    rf.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
                }
            }
        } catch (Exception e) {
            Logger.getLogger(LoginSystem.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jLoginButtonActionPerformed

    private void jtxtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtUsernameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                String username = jtxtUsername.getText();
                String password = String.valueOf(jtxtPassword.getPassword());

                conn = DriverManager.getConnection(URL, USERNAME, PASSWORD);
                ps = conn.prepareStatement("SELECT * FROM customer "
                        + "WHERE username = ? AND BINARY password = ?");

                ps.setString(1, username);
                ps.setString(2, password);

                rset = ps.executeQuery();

                if (rset.next()) {
                    if (jtxtUsername.getText().equals("admin") && jtxtUsername.getText().equals("admin")) {
                        JOptionPane.showMessageDialog(null, "Logged in successfully!", "WELCOME ADMIN!", 1);
                        adminPanel aP = new adminPanel();
                        aP.setVisible(true);
                        aP.setLocationRelativeTo(this);
                        aP.setSize(926, 546);
                        this.dispose();

                        adminPanel.WelcomeUser.setText("WELCOME, " + LoginSystem.jtxtUsername.getText().toUpperCase() + "!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Logged in successfully!", "SUCCESS!", 1);
                        JPsOnlineShopping jpos = new JPsOnlineShopping();
                        jpos.setVisible(true);
                        jpos.setLocationRelativeTo(this);
                        jpos.setSize(926, 546);
                        this.dispose();

                        String cid = rset.getString("customer_id");
                        String address = rset.getString("address");
                        JPsOnlineShopping.lblID.setText(cid);
                        JPsOnlineShopping.CAddress.setText(address);

                        JPsOnlineShopping.WelcomeUser.setText("welcome, " + LoginSystem.jtxtUsername.getText().toLowerCase() + "!");
                        jpos.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Invalid username/password!", "LOGIN FAILED!", 2);
                    tries--;
                    if (tries == 0) {
                        tries = 3;
                        JOptionPane.showMessageDialog(null, "Redirecting you to create a new account!", "LOGIN FAILED!", 2);
                        RegisterForm rf = new RegisterForm();
                        rf.setVisible(true);
                        rf.setLocationRelativeTo(this);
                        rf.setSize(926, 546);
                        rf.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
                    }
                }
            } catch (Exception e) {
                Logger.getLogger(LoginSystem.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_jtxtUsernameKeyPressed

    private void jtxtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                String username = jtxtUsername.getText();
                String password = String.valueOf(jtxtPassword.getPassword());

                conn = DriverManager.getConnection(URL, USERNAME, PASSWORD);
                ps = conn.prepareStatement("SELECT * FROM customer "
                        + "WHERE username = ? AND BINARY password = ?");

                ps.setString(1, username);
                ps.setString(2, password);

                rset = ps.executeQuery();

                if (rset.next()) {
                    if (jtxtUsername.getText().equals("admin") && jtxtUsername.getText().equals("admin")) {
                        JOptionPane.showMessageDialog(null, "Logged in successfully!", "WELCOME ADMIN!", 1);
                        adminPanel aP = new adminPanel();
                        aP.setVisible(true);
                        aP.setLocationRelativeTo(this);
                        aP.setSize(926, 546);
                        this.dispose();

                        adminPanel.WelcomeUser.setText("WELCOME, " + LoginSystem.jtxtUsername.getText().toUpperCase() + "!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Logged in successfully!", "SUCCESS!", 1);
                        JPsOnlineShopping jpos = new JPsOnlineShopping();
                        jpos.setVisible(true);
                        jpos.setLocationRelativeTo(this);
                        jpos.setSize(926, 546);
                        this.dispose();

                        String cid = rset.getString("customer_id");
                        String address = rset.getString("address");
                        JPsOnlineShopping.lblID.setText(cid);
                        JPsOnlineShopping.CAddress.setText(address);

                        JPsOnlineShopping.WelcomeUser.setText("welcome, " + LoginSystem.jtxtUsername.getText().toLowerCase() + "!");
                        jpos.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Invalid username/password!", "LOGIN FAILED!", 2);
                    tries--;
                    if (tries == 0) {
                        tries = 3;
                        JOptionPane.showMessageDialog(null, "Redirecting you to create a new account!", "LOGIN FAILED!", 2);
                        RegisterForm rf = new RegisterForm();
                        rf.setVisible(true);
                        rf.setLocationRelativeTo(this);
                        rf.setSize(926, 546);
                        rf.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
                    }
                }
            } catch (Exception e) {
                Logger.getLogger(LoginSystem.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_jtxtPasswordKeyPressed

    private void HealPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HealPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HealPanelMousePressed

    private void HealPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HealPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HealPanelMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
                new Runnable() {
            public void run() {
                new LoginSystem().setVisible(true);
            }
        }
        );

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeadLabel;
    private javax.swing.JPanel HealPanel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JButton jBtnClose;
    private javax.swing.JButton jBtnMinimize;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JCheckBox jShowPass;
    private javax.swing.JLabel jicoUser;
    private javax.swing.JLabel jlblPass;
    private javax.swing.JLabel jlblPassword;
    private javax.swing.JLabel jlblQuestion;
    private javax.swing.JLabel jlblUsername;
    private javax.swing.JPasswordField jtxtPassword;
    public static javax.swing.JTextField jtxtUsername;
    private javax.swing.JLabel registerLink;
    // End of variables declaration//GEN-END:variables
}
