/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online_shopping_system;

import java.sql.*;
import java.util.logging.*; //gets Level and Logger
import javax.swing.*; // gets JFrame and JOptionPane
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.ButtonGroup;

/**
 *
 * @author MIRAFLORES, JOHN PAUL S. - BSIT 2F
 */
public class RegisterForm extends javax.swing.JFrame {

    private static final String URL = "jdbc:mysql://localhost:3306/online_shopping_system?allowPublicKeyRetrieval=true&useSSL=false";
    private static final String USERNAME = "root";
    private static final String PASSWORD = "@theHouseof25";

    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rset = null;
    SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd");

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();

        jtxtPassword.setEchoChar('●');
        jtxtConfirmPassword.setEchoChar('●');

        this.setSize(926, 546);
        this.setLocationRelativeTo(null);

        String checkboxAgree = "<html>I agree to the <u>Terms of Service</u> and <u>Privacy Policy</u>.</html>";
        agreeChkBox.setText(checkboxAgree);

        String underline = "<html><u>click here to login!</u></html>";
        registerLink.setText(underline);

        ButtonGroup sex = new ButtonGroup();
        sex.add(jRBtnMale);
        sex.add(jRBtnFemale);

        jCreateButton.setEnabled(false);

    }

    int xMouse;
    int yMouse;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeadPanel = new javax.swing.JPanel();
        jCloseButton = new javax.swing.JButton();
        jMinimizeButton = new javax.swing.JButton();
        HeadLabel = new javax.swing.JLabel();
        RegistrationPanel = new javax.swing.JPanel();
        jtxtLName = new javax.swing.JTextField();
        jtxtPassword = new javax.swing.JPasswordField();
        jCreateButton = new javax.swing.JButton();
        jlblQuestion = new javax.swing.JLabel();
        registerLink = new javax.swing.JLabel();
        jlblPass = new javax.swing.JLabel();
        jlblLName = new javax.swing.JLabel();
        jShowPass = new javax.swing.JCheckBox();
        jtxtConfirmPassword = new javax.swing.JPasswordField();
        jlblConfirm = new javax.swing.JLabel();
        jtxtUsername = new javax.swing.JTextField();
        jlblUser = new javax.swing.JLabel();
        jtxtFName = new javax.swing.JTextField();
        jlblFName = new javax.swing.JLabel();
        jlblBirthDate = new javax.swing.JLabel();
        jlblAddress = new javax.swing.JLabel();
        jtxtAddress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jlblEmail = new javax.swing.JLabel();
        jtxtContact = new javax.swing.JTextField();
        jlblContact = new javax.swing.JLabel();
        jtxtCity = new javax.swing.JTextField();
        jlblCity = new javax.swing.JLabel();
        jtxtZip = new javax.swing.JTextField();
        jlblZip = new javax.swing.JLabel();
        forLockAspect = new javax.swing.JLabel();
        jlblSex = new javax.swing.JLabel();
        jRBtnMale = new javax.swing.JRadioButton();
        jRBtnFemale = new javax.swing.JRadioButton();
        jtxtBirthDate = new com.toedter.calendar.JDateChooser();
        agreeChkBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        HeadPanel.setBackground(new java.awt.Color(15, 45, 66));
        HeadPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeadPanelMouseDragged(evt);
            }
        });
        HeadPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeadPanelMousePressed(evt);
            }
        });
        HeadPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCloseButton.setBackground(new java.awt.Color(0, 102, 204));
        jCloseButton.setFont(new java.awt.Font("Gulim", 0, 18)); // NOI18N
        jCloseButton.setForeground(new java.awt.Color(255, 255, 255));
        jCloseButton.setText("x");
        jCloseButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCloseButtonActionPerformed(evt);
            }
        });
        HeadPanel.add(jCloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(871, 27, 27, -1));

        jMinimizeButton.setBackground(new java.awt.Color(0, 102, 204));
        jMinimizeButton.setFont(new java.awt.Font("Gulim", 0, 18)); // NOI18N
        jMinimizeButton.setForeground(new java.awt.Color(255, 255, 255));
        jMinimizeButton.setText("-");
        jMinimizeButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMinimizeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMinimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMinimizeButtonActionPerformed(evt);
            }
        });
        HeadPanel.add(jMinimizeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 27, 27, -1));

        HeadLabel.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        HeadLabel.setForeground(new java.awt.Color(255, 255, 255));
        HeadLabel.setText("JP's JEWELRY SHOPPING | CREATE AN ACCOUNT");
        HeadPanel.add(HeadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 25, -1, -1));

        RegistrationPanel.setBackground(new java.awt.Color(108, 122, 137));
        RegistrationPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtLName.setBackground(new java.awt.Color(15, 45, 66));
        jtxtLName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtLName.setForeground(new java.awt.Color(255, 255, 255));
        jtxtLName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        RegistrationPanel.add(jtxtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 171, -1));

        jtxtPassword.setBackground(new java.awt.Color(15, 45, 66));
        jtxtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtPassword.setForeground(new java.awt.Color(153, 153, 153));
        jtxtPassword.setText("●●●●●●●●");
        jtxtPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtPasswordFocusLost(evt);
            }
        });
        RegistrationPanel.add(jtxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 354, -1));

        jCreateButton.setBackground(new java.awt.Color(15, 45, 66));
        jCreateButton.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jCreateButton.setForeground(new java.awt.Color(255, 255, 255));
        jCreateButton.setText("CREATE");
        jCreateButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jCreateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateButtonActionPerformed(evt);
            }
        });
        RegistrationPanel.add(jCreateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 70, 30));

        jlblQuestion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblQuestion.setForeground(new java.awt.Color(255, 255, 255));
        jlblQuestion.setText("already have an account?");
        RegistrationPanel.add(jlblQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, 30));

        registerLink.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        registerLink.setForeground(new java.awt.Color(255, 255, 255));
        registerLink.setText("click here to login!");
        registerLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerLinkMouseClicked(evt);
            }
        });
        RegistrationPanel.add(registerLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, 30));

        jlblPass.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblPass.setForeground(new java.awt.Color(255, 255, 255));
        jlblPass.setText("password:");
        RegistrationPanel.add(jlblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jlblLName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblLName.setForeground(new java.awt.Color(255, 255, 255));
        jlblLName.setText("last name: ");
        RegistrationPanel.add(jlblLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        jShowPass.setForeground(new java.awt.Color(255, 255, 255));
        jShowPass.setText("show password");
        jShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowPassActionPerformed(evt);
            }
        });
        RegistrationPanel.add(jShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        jtxtConfirmPassword.setBackground(new java.awt.Color(15, 45, 66));
        jtxtConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtConfirmPassword.setForeground(new java.awt.Color(153, 153, 153));
        jtxtConfirmPassword.setText("●●●●●●●●");
        jtxtConfirmPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtConfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtConfirmPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtConfirmPasswordFocusLost(evt);
            }
        });
        RegistrationPanel.add(jtxtConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 354, -1));

        jlblConfirm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblConfirm.setForeground(new java.awt.Color(255, 255, 255));
        jlblConfirm.setText("confirm password:");
        RegistrationPanel.add(jlblConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jtxtUsername.setBackground(new java.awt.Color(15, 45, 66));
        jtxtUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtUsername.setForeground(new java.awt.Color(255, 255, 255));
        jtxtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        RegistrationPanel.add(jtxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 354, -1));

        jlblUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblUser.setForeground(new java.awt.Color(255, 255, 255));
        jlblUser.setText("username: ");
        RegistrationPanel.add(jlblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jtxtFName.setBackground(new java.awt.Color(15, 45, 66));
        jtxtFName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtFName.setForeground(new java.awt.Color(255, 255, 255));
        jtxtFName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        RegistrationPanel.add(jtxtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 171, -1));

        jlblFName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblFName.setForeground(new java.awt.Color(255, 255, 255));
        jlblFName.setText("first name: ");
        RegistrationPanel.add(jlblFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jlblBirthDate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblBirthDate.setForeground(new java.awt.Color(255, 255, 255));
        jlblBirthDate.setText("birthdate: ");
        RegistrationPanel.add(jlblBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        jlblAddress.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblAddress.setForeground(new java.awt.Color(255, 255, 255));
        jlblAddress.setText("address: ");
        RegistrationPanel.add(jlblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        jtxtAddress.setBackground(new java.awt.Color(15, 45, 66));
        jtxtAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtAddress.setForeground(new java.awt.Color(255, 255, 255));
        jtxtAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        RegistrationPanel.add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 342, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online_shopping_system/Assets/EYEpixel.gif"))); // NOI18N
        RegistrationPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 100, 68));

        jtxtEmail.setBackground(new java.awt.Color(15, 45, 66));
        jtxtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtEmail.setForeground(new java.awt.Color(255, 255, 255));
        jtxtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        RegistrationPanel.add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 342, -1));

        jlblEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblEmail.setForeground(new java.awt.Color(255, 255, 255));
        jlblEmail.setText("e-mail: ");
        RegistrationPanel.add(jlblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        jtxtContact.setBackground(new java.awt.Color(15, 45, 66));
        jtxtContact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtContact.setForeground(new java.awt.Color(255, 255, 255));
        jtxtContact.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtContactKeyTyped(evt);
            }
        });
        RegistrationPanel.add(jtxtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 342, -1));

        jlblContact.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblContact.setForeground(new java.awt.Color(255, 255, 255));
        jlblContact.setText("phone number: ");
        RegistrationPanel.add(jlblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        jtxtCity.setBackground(new java.awt.Color(15, 45, 66));
        jtxtCity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtCity.setForeground(new java.awt.Color(255, 255, 255));
        jtxtCity.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        RegistrationPanel.add(jtxtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 165, -1));

        jlblCity.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblCity.setForeground(new java.awt.Color(255, 255, 255));
        jlblCity.setText("city: ");
        RegistrationPanel.add(jlblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        jtxtZip.setBackground(new java.awt.Color(15, 45, 66));
        jtxtZip.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtZip.setForeground(new java.awt.Color(255, 255, 255));
        jtxtZip.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtZip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtZipKeyTyped(evt);
            }
        });
        RegistrationPanel.add(jtxtZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 160, -1));

        jlblZip.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblZip.setForeground(new java.awt.Color(255, 255, 255));
        jlblZip.setText("zip: ");
        RegistrationPanel.add(jlblZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, -1, -1));

        forLockAspect.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        forLockAspect.setForeground(new java.awt.Color(255, 255, 255));
        RegistrationPanel.add(forLockAspect, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 462, 120, -1));

        jlblSex.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblSex.setForeground(new java.awt.Color(255, 255, 255));
        jlblSex.setText("sex: ");
        RegistrationPanel.add(jlblSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, 40));

        jRBtnMale.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jRBtnMale.setSelected(true);
        jRBtnMale.setText("male");
        RegistrationPanel.add(jRBtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, 40));

        jRBtnFemale.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jRBtnFemale.setText("female");
        RegistrationPanel.add(jRBtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, 40));

        jtxtBirthDate.setBackground(new java.awt.Color(15, 45, 66));
        jtxtBirthDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtxtBirthDate.setForeground(new java.awt.Color(153, 153, 153));
        jtxtBirthDate.setDateFormatString("MMM dd, yyyy");
        jtxtBirthDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RegistrationPanel.add(jtxtBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 340, 30));

        agreeChkBox.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        agreeChkBox.setForeground(new java.awt.Color(255, 255, 255));
        agreeChkBox.setText("I agree to the Terms of Service and Privacy Policy.");
        agreeChkBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agreeChkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreeChkBoxActionPerformed(evt);
            }
        });
        RegistrationPanel.add(agreeChkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HeadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(RegistrationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(RegistrationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private JFrame frame;
    private void jCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCloseButtonActionPerformed
        frame = new JFrame("Close");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure you want to exit?", "Online Shopping",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jCloseButtonActionPerformed

    private void jMinimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMinimizeButtonActionPerformed
        this.setState(frame.ICONIFIED);
    }//GEN-LAST:event_jMinimizeButtonActionPerformed

    private void registerLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLinkMouseClicked
        LoginSystem ls = new LoginSystem();
        ls.setVisible(true);
        ls.setLocationRelativeTo(this);
        ls.setSize(926, 546);
        ls.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_registerLinkMouseClicked

    private void jShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowPassActionPerformed
        if (jShowPass.isSelected()) {
            jtxtPassword.setEchoChar((char) 0);
        } else {
            jtxtPassword.setEchoChar('●');
        }
    }//GEN-LAST:event_jShowPassActionPerformed

    private void jtxtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPasswordFocusGained
        String password = String.valueOf(jtxtPassword.getPassword());

        if (password.trim().toLowerCase().equals("●●●●●●●●")) {
            jtxtPassword.setText("");
            jtxtPassword.setForeground(Color.white);
        }
    }//GEN-LAST:event_jtxtPasswordFocusGained

    private void jtxtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPasswordFocusLost
        String password = String.valueOf(jtxtPassword.getPassword());

        if (password.trim().equals("") || password.trim().toLowerCase().equals("●●●●●●●●")) {
            jtxtPassword.setText("●●●●●●●●");
            jtxtPassword.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jtxtPasswordFocusLost

    private void jtxtConfirmPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtConfirmPasswordFocusGained
        String retypepassword = String.valueOf(jtxtConfirmPassword.getPassword());

        if (retypepassword.trim().toLowerCase().equals("●●●●●●●●")) {
            jtxtConfirmPassword.setText("");
            jtxtConfirmPassword.setForeground(Color.white);
        }
    }//GEN-LAST:event_jtxtConfirmPasswordFocusGained

    private void jtxtConfirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtConfirmPasswordFocusLost
        String retypepassword = String.valueOf(jtxtConfirmPassword.getPassword());

        if (retypepassword.trim().equals("") || retypepassword.trim().toLowerCase().equals("●●●●●●●●")) {
            jtxtConfirmPassword.setText("●●●●●●●●");
            jtxtConfirmPassword.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jtxtConfirmPasswordFocusLost

    private void jtxtContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtContactKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        } // makes the jtxtField type numbers only
    }//GEN-LAST:event_jtxtContactKeyTyped

    private void jtxtZipKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtZipKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        } // makes the jtxtField type numbers only
    }//GEN-LAST:event_jtxtZipKeyTyped

    private void jCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateButtonActionPerformed
        String username = jtxtUsername.getText();
        String fname = jtxtFName.getText();
        String lname = jtxtLName.getText();
        String password = String.valueOf(jtxtPassword.getPassword());
        String sex = "male";
        String email = jtxtEmail.getText();
        String contactnumber = jtxtContact.getText();
        String birthdate = Date_Format.format(jtxtBirthDate.getDate());
        String address = jtxtAddress.getText();
        String city = jtxtCity.getText();
        String zip = jtxtZip.getText();

        if (jRBtnFemale.isSelected()) {
            sex = "female";
        }

        if (verifyFields()) {
            if (!checkUsername(username)) {
                try {
                    conn = DriverManager.getConnection(URL, USERNAME, PASSWORD);
                    ps = conn.prepareStatement("INSERT INTO customer "
                            + "(FNAME,LNAME,CUSTOMER_EMAIL,CUSTOMER_PNUMBER,ADDRESS,CITY,ZIP,birthdate,password,username,sex) "
                            + "VALUES(?,?,?,?,?,?,?,?,?,?,?)");
                    ps.setString(1, fname);
                    ps.setString(2, lname);
                    ps.setString(3, email);
                    ps.setString(4, contactnumber);
                    ps.setString(5, address);
                    ps.setString(6, city);
                    ps.setString(7, zip);
                    ps.setString(8, birthdate);
                    ps.setString(9, password);
                    ps.setString(10, username.replaceAll(" ", ""));
                    ps.setString(11, sex);

                    if (ps.executeUpdate() != 0) {
                        JOptionPane.showMessageDialog(null, "Your account has been created!");
                        LoginSystem ls = new LoginSystem();
                        // for transferring data to another frame
                        // also, make both the variables a public static so you can transfer it
                        ls.setVisible(true);
                        ls.setLocationRelativeTo(this);
                        ls.setSize(926, 546);
                        ls.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Error! Please check your information!");
                    }
                } catch (Exception e) {
                    Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, e);
                }
            }
        }
    }//GEN-LAST:event_jCreateButtonActionPerformed

    private void agreeChkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreeChkBoxActionPerformed
        if (agreeChkBox.isSelected()) {
            jCreateButton.setEnabled(true);
        } else {
            jCreateButton.setEnabled(false);
        }
    }//GEN-LAST:event_agreeChkBoxActionPerformed

    private void HeadPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeadPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeadPanelMousePressed

    private void HeadPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeadPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HeadPanelMouseDragged

    public boolean verifyFields() {
        String username = jtxtUsername.getText();
        String fname = jtxtFName.getText();
        String lname = jtxtLName.getText();
        String password = String.valueOf(jtxtPassword.getPassword());
        String confirmpassword = String.valueOf(jtxtConfirmPassword.getPassword());
        String email = jtxtEmail.getText();
        String contactnumber = jtxtContact.getText();
        String birthdate = Date_Format.format(jtxtBirthDate.getDate());
        String address = jtxtAddress.getText();
        String city = jtxtCity.getText();
        String zip = jtxtZip.getText();

        // checking if the fields are empty
        if (username.trim().equals("")
                || fname.trim().equals("")
                || lname.trim().equals("")
                || password.trim().equals("password")
                || confirmpassword.trim().equals("password")
                || email.trim().equals("")
                || contactnumber.trim().equals("")
                || birthdate.trim().equals("")
                || address.trim().equals("")
                || city.trim().equals("")
                || zip.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "One or more fields are empty!", "Empty Fields", 2);
            return false;
        } else if (!password.equals(confirmpassword)) //check if password and password confirmation are equal
        {
            JOptionPane.showMessageDialog(null, "Passwords doesn't match!", "Confirm password!", 2);
            return false;
        } else // if everything is fine
        {
            return true;
        }
    }

    public boolean checkUsername(String username) {

        boolean username_exists = false;

        try {
            conn = DriverManager.getConnection(URL, USERNAME, PASSWORD);
            ps = conn.prepareStatement("SELECT * FROM customer WHERE username = ?");

            ps.setString(1, username);
            rset = ps.executeQuery();

            if (rset.next()) {
                username_exists = true;
                JOptionPane.showMessageDialog(null, "Sorry, This username already existed! Try another username", "Username exists!", 2);
            }

        } catch (Exception e) {
            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, e);
        }

        return username_exists;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeadLabel;
    private javax.swing.JPanel HeadPanel;
    private javax.swing.JPanel RegistrationPanel;
    private javax.swing.JCheckBox agreeChkBox;
    private javax.swing.JLabel forLockAspect;
    private javax.swing.JButton jCloseButton;
    private javax.swing.JButton jCreateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jMinimizeButton;
    private javax.swing.JRadioButton jRBtnFemale;
    private javax.swing.JRadioButton jRBtnMale;
    private javax.swing.JCheckBox jShowPass;
    private javax.swing.JLabel jlblAddress;
    private javax.swing.JLabel jlblBirthDate;
    private javax.swing.JLabel jlblCity;
    private javax.swing.JLabel jlblConfirm;
    private javax.swing.JLabel jlblContact;
    private javax.swing.JLabel jlblEmail;
    private javax.swing.JLabel jlblFName;
    private javax.swing.JLabel jlblLName;
    private javax.swing.JLabel jlblPass;
    private javax.swing.JLabel jlblQuestion;
    private javax.swing.JLabel jlblSex;
    private javax.swing.JLabel jlblUser;
    private javax.swing.JLabel jlblZip;
    private javax.swing.JTextField jtxtAddress;
    private com.toedter.calendar.JDateChooser jtxtBirthDate;
    private javax.swing.JTextField jtxtCity;
    private javax.swing.JPasswordField jtxtConfirmPassword;
    private javax.swing.JTextField jtxtContact;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFName;
    private javax.swing.JTextField jtxtLName;
    private javax.swing.JPasswordField jtxtPassword;
    public static javax.swing.JTextField jtxtUsername;
    private javax.swing.JTextField jtxtZip;
    private javax.swing.JLabel registerLink;
    // End of variables declaration//GEN-END:variables
}
